ALTER TABLE profiles ADD COLUMN IF NOT EXISTS country TEXT;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS streak_days INT NOT NULL DEFAULT 0;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS last_practice_date DATE;
ALTER TABLE profiles ADD COLUMN IF NOT EXISTS total_talk_seconds BIGINT NOT NULL DEFAULT 0;
